version: "3.8"
services:
  pytorch:
    container_name: pytorch
    image: registry.cn-shenzhen.aliyuncs.com/ai_base/pytorch:1.14.0
    build:
      context: .
    ports:
      - 127.0.0.1:5000:5000
      - 9090:22
      - 8889:8889
      - 8080:8080
    tty: true
    ipc: host
    environment:
      CLI_ARGS: ""
      SAFETENSORS_FAST_GPU: 1
      DISPLAY: $DISPLAY
    tmpfs:
      - /tmp
    volumes:
      - ./data:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0' ]
              capabilities: [ gpu ]
    restart: always
